[package]
name = "tui-counters"
version = "0.3.0"
edition = "2021"
repository = "https://github.com/IRSMsoso/tui-counters"
description = "Simple counters TUI"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
ratatui = "0.27.0"
anyhow = "1.0.86"
tui-input = "0.9.0"